### ISSUE TITLE
Add wishlist

### ISSUE THREAD

**Issue by chazzels** [chazzels/Spectrum#10]
Wishlist button added. does not currently link to any pages on the dev site.

**Comment by ericspectrum** [comment]
this also needs some sort of UI to show that something has already been wishlisted.

**Comment by chazzels** [comment]
Pages linked. UI to show item as been added to wishlist functioning. 
 
Page that displays complete wishlist needs to be styled still.  Will use design elements and concepts from cart page.

**Comment by chazzels** [comment]
threw some simple style improvements up for the page
