### ISSUE TITLE
Add product reviews 

### ISSUE THREAD

**Issue by chazzels** [chazzels/Spectrum#13]
need clarification on what plugin / system is being used for this.

**Comment by chazzels** [comment]
"Coming soon" added as temporary text for now.

**Comment by ericspectrum** [comment]
Up to Sal, we have to have something by re-launch.  100% i don't care what it is.

**Comment by chazzels** [comment]
I have a comments enabled and displaying on the products. the only question is how do you want to collect comments? do you want a form submission on the product page or are you collecting the reviews post purchase as verified buyers of the product? 

p.s. the submission form on the product page default setup is that it would require a account with the website to help trim down on spam. This can be disabled allowing anyone (even bots/crawlers) to comment. 
(All Comment have to approve in the back end before being displayed currently. )

**Comment by salbono** [comment]
I think a form when logged in will be great. If not logged in we should have a link to the account page where they can create an account. IT should read "Please log in or create an account to leave a review of this product."

**Comment by chazzels** [comment]
currently having issues with the comment submit form displaying. looking into potential root issues to the problem. Have tried multiple methods of placing the form but no luck.
