### ISSUE TITLE
Freebies

### ISSUE THREAD

**Issue by chazzels** [chazzels/Spectrum#25]
What Items are freebies and how many freebies can one user have?

**Comment by ericspectrum** [comment]
freebies will be a category, and i'm assuming for now we will only let them pick one out of like 4 choices.  that is the complexity difference to let them choose more than 1?

**Comment by zoeligon** [comment]
I'm actually going to nix freebies for this sprint -- honestly i only give people little lube packets so there isn't much selection anyway. let's handle this later.

**Comment by salbono** [comment]
Sounds god to me
