### ISSUE TITLE
add secure checkout to checkout page

### ISSUE THREAD

**Issue by chazzels** [chazzels/Spectrum#3]
I know the text "secure checkout" was wanted on the checkout page but will this be a real SSL Connection with valid certs? if so those certs need to get obtained before this can move forward. If not then that is not a real secure checkout.

**Comment by ericspectrum** [comment]
good point, Sal what is needed for this?  Isn't woo secure anyway?

**Comment by zoeligon** [comment]
we can have a paypal verified seller button perhaps?

**Comment by salbono** [comment]
I think paypal verified seller would be a good trust flair.

**Comment by salbono** [comment]
Since we are pressing payment via paypal we should be able to use the "secure checkout" text. I will look into SSL as well for added security.
