### ISSUE TITLE
add prices back to grid views

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#32]
https://www.dropbox.com/work/Spectrum%20Boutique%20Team%20Folder/Spectrum%20Documents/Web/Web%20Comps-%20from%20OTHER/Desktop%20PSDs?preview=Spectrum_Sub_Categories_Prices_010116.psd

here is the styling.  until we decide to remove brands officially, the prices should go underneath (by brand)

**Comment by chazzels** [comment]
Unfortunately this link does not work for me.

**Comment by ericspectrum** [comment]
![image](https://cloud.githubusercontent.com/assets/16167470/13062537/08e278ea-d405-11e5-84e8-6c5c81b6902e.png)

**Comment by salbono** [comment]
Brand name removed and price added per design mock up
