### ISSUE TITLE
coupon text is wrong and formatting of box sizes is off

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#35]
should just see enter coupon code - and be big enough that it doesn't get cut off.

the coupon code box and the plus sign box are not the same size.  look terrible.

**Comment by ericspectrum** [comment]
its even worse on mobile

**Comment by salbono** [comment]
Text was originally changed to match the mock ups. Due to responsiveness, longer text will be an issue. Changed back to enter coupon.
