### ISSUE TITLE
what happened to cross or upsells in cart?

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#38]

**Comment by salbono** [comment]
Will check in with Charles in this. I haven't added or removed these from the cart.

**Comment by chazzels** [comment]
I took out the freebies because that is what was stated was wanted on an earlier issue. 

Cross sells Im not sure why they are not showing. could be a migration conflict. Will begin problem solving issue

**Comment by chazzels** [comment]
Upon reviewing designs no upsells section is shown so it was removed from cart. 

Freebies where removed back in issue #25 Freebies by @zoeligon. 

So as a result the cart page has no upsells or cross sells as pre design and input received

**Comment by ericspectrum** [comment]
i guess that makes sense.  I'd like to put the upsells back in the cart if we're taking out the freebies.  I'd like it to be a slider like we are going to do for the spectrum recommends.

**Comment by salbono** [comment]
added
