### ISSUE TITLE
cart steps status missing on mobile

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#40]
see checkout mockup

https://www.dropbox.com/work/Spectrum%20Boutique%20Team%20Folder/Spectrum%20Documents/Web/Web%20Comps-%20from%20OTHER/Mobile%20PSDs?preview=SB_Mobile_Checkout.psd

**Comment by salbono** [comment]
Should only be missing from cart page. Had to be hard coded into php.

**Comment by salbono** [comment]
Had to be hard coded into php.
