### ISSUE TITLE
Confirmation page and confirmation email

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#47]
i know there was some difficulty with customizing the confirmation page, but i know you can have it send you to a different page altogether.  so obviously lets do that. this page is soooooo important.  right now its like you win a video game and the tv just shuts off.  its the least climactic thing you can imagine.  terrible customer experience.  

ALSO

the email you get after you place an order???  it comes from a crazy address and it looks like windows 98 styling.  not on brand at all.  How do we fix the send address most importantly and then make it look exactly like our on screen confirmation.  Right now it comes from a blue host address... not ok.

**Comment by salbono** [comment]
Confirmation page has been restyled and uploaded. Still have to add email sign up to page. 

Will check into copy/paste .php into email form for confirmation email. If styling this email is a whole lot more in depth than this it will require additional hours.
