### ISSUE TITLE
If we are using paypal, shouldn't there be a way to skip the form on checkout? 

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#48]
pay pal is gonna have all that info anyway.

**Comment by salbono** [comment]
Woocommerce requires users to fill out information by default regardless of layment gateway. Will research to see if we can bypass this.

**Comment by chazzels** [comment]
Looked into solutions to bypass this behavior correctly. WooCommerce does not offer a native solution to this but a plugin called Paypal Express Checkout seems to take care of all the back-end + front-end issues as well as offer official paypal graphic buttons. This may be the quickest and most reliable solution to this problem

Link to plugin page:
[https://www.woothemes.com/products/paypal-express-checkout/](url)

**Comment by salbono** [comment]
Should be http://www.woothemes.com/products/paypal-express. 

Looks pretty straight forward of you decide want to implement it and doesn't really need any dev, just set up.
