### ISSUE TITLE
email list was removed when we changed modal. HI PRIORITY

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#50]
i made a new pop-up modal that comes on when you go to the cart!! check it out :)

BUT we need a join the email list thing in the footer under connect.  it could either be a small version of the form itself or a link to "Join our Email List" that opens up a small modal with the form for submission.

Please do this ASAP  higher priority than almost anything else.  thanks

**Comment by chazzels** [comment]
Join email list form added but i needs to be linked into your mailchip account i believe. @salbono is much more experienced with mailchimp than me so I will have take a look at it and hide it for now.

**Comment by salbono** [comment]
Please hide this. I will style accordingly

**Comment by chazzels** [comment]
it is hiding in the first footer column

**Comment by salbono** [comment]
Input in modal restyled and link to "join newsletter" that activates modal now in footer
