### ISSUE TITLE
Hi Priority - Remove all stock values

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#51]
Not sure what or when something went wrong that is causing 0 stock to show for many items, and wrong stock for others, but until its totally resolved, all stock quantities need to be removed from the site.

they appear or have appeared on:
product pages
cart pages
checkout page

please make stock quantity not visible anywhere on the site.  this is a high priority task

**Comment by chazzels** [comment]
stock removed from desired locations
