### ISSUE TITLE
Font handling for IE - BUG

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#52]
IE is not handling the fonts on the site properly.  look at the home page in IE.  the title fonts are off.

**Comment by chazzels** [comment]
IE requires a special font format. just need to convert fonts, upload to server and configure the IE fonts in styles.

**Comment by ericspectrum** [comment]
now the font is wrong for chrome..... this is def worse!!!

**Comment by chazzels** [comment]
Settle down I ran into some development problems. I will have them resolved by tonight. IE is behaving oddly and the current font system was spread across 4 files making it near impossible to troubleshoot. I am condense and simplifying the code. This takes time unfortunately.

**Comment by ericspectrum** [comment]
Then don't do it live.  That's why there is a testing site.  Were you not aware that you should prob test things before you push them?

**Comment by chazzels** [comment]
it was mistake that I cant roll back. so sit tight and stop complaining. I will fix what I messed up. 

BTW

**Comment by ericspectrum** [comment]
please do, the mobile site is entirely down right now
