### ISSUE TITLE
after you add to wishlist, formatting is weird

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#53]
can we have shipping info on the next line so it doesnt get split in half.  gonna upload a screenshot

**Comment by ericspectrum** [comment]
![image](https://cloud.githubusercontent.com/assets/16167470/13091613/9a6dbcb8-d4c1-11e5-99c7-25529298b2d4.png)

**Comment by chazzels** [comment]
styles need some tweaking but all fixed and tested on mobile as well as desktop
