### ISSUE TITLE
Did you design in the second h1 title for product description??

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#54]
in the new product page design there is a 2nd h1 title.  did we add?

it will look like:
h1 - product name by brand
h1(2) -product description

Vixskin Outlaw by Vixen
Washable, Harnessable, flesh colored dildo

**Comment by ericspectrum** [comment]
![image](https://cloud.githubusercontent.com/assets/16167470/13091885/d2d87916-d4c2-11e5-811f-a62c914832de.png)

**Comment by ericspectrum** [comment]
![image](https://cloud.githubusercontent.com/assets/16167470/13091904/e62db6fc-d4c2-11e5-875a-cdf962e2eb3e.png)

**Comment by salbono** [comment]
Product short description is now showing below title. Descriptions need to be added as <h1 class="short-description">Short description here<h1>

See test product in backend for reference

**Comment by ericspectrum** [comment]
Ya we know we have to go back and edit them all. Annoying for us.  Thank you. Do u have a laugh for test product?

**Comment by salbono** [comment]
Laugh?

**Comment by ericspectrum** [comment]
Oh I meant slug. Weird autocorrect. I found it. It looks dope.
