### ISSUE TITLE
2 up grid on all pages

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#55]
right now the 2 up grid is only on the grid pages, but it needs to be that way on all pages.  product pages, cart pages, all pages.  this means recommended products, upsells, cross sells etc.

eventually the recommended products will be a slider like i said, but whenever its handled the way it is now it should 2 up.

**Comment by salbono** [comment]
Other than "recommends" this is working. recommends will com in line when new select option is introduced
