### ISSUE TITLE
wishlist should be styled like cart on mobile

### ISSUE THREAD

**Issue by ericspectrum** [chazzels/Spectrum#56]
anyway to recycle the code from the cart to the wishlist.  looks pretty bad on mobile.

**Comment by chazzels** [comment]
There is no way to recycle that code. It is very specialized to the cart and its functions.

**Comment by chazzels** [comment]
we will apply some mobile styles to clean it up but we will not be rewriting this code

**Comment by chazzels** [comment]
style applied to separate products from one another, borders cleaned up as well.

**Comment by ericspectrum** [comment]
can you remove unit from "unit price" so it just says price.

**Comment by salbono** [comment]
I'll take care of that

**Comment by ericspectrum** [comment]
thanks
