### ISSUE TITLE
Rework Checkout to div

### ISSUE THREAD

**Issue by chazzels** [chazzels/Spectrum#8]
I have looked into this and still sorting some issues that might arise due to how the form data is collected. Will research possible solutions and consider other methods

**Comment by chazzels** [comment]
This I have discovered will take a massive amount of time. the page is split among 8 files not including the js that might have to be rewritten to support. styling is still possible.

**Comment by chazzels** [comment]
This Is almost done. ran into some styling issues. have resolved and putting the last touches on this section.

**Comment by salbono** [comment]
Awesome! Let's finish up the styling and see get this completed by the end of the day.
